export const EVENTS = [
 {
  "id": "evt-9",
  "title": "PS 137K Thurs",
  "school": "PS 137K Thurs",
  "address": "123 Main St",
  "subway": "1, 2, 3",
  "type": "Camp",
  "dayOfWeek": "Thursday",
  "date": "2026-07-13",
  "status": "Active",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-7",
  "title": "PS 137K Thurs",
  "school": "PS 137K Thurs",
  "address": "123 Main St",
  "subway": "1, 2, 3",
  "type": "Camp",
  "dayOfWeek": "Thursday",
  "date": "2026-07-14",
  "status": "Active",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-8",
  "title": "PS 137K Thurs",
  "school": "PS 137K Thurs",
  "address": "123 Main St",
  "subway": "1, 2, 3",
  "type": "Camp",
  "dayOfWeek": "Thursday",
  "date": "2026-07-20",
  "status": "Active",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-11",
  "title": "MS 371x",
  "school": "MS 371x",
  "address": "650 hollywood ave Bronx",
  "subway": "",
  "type": "Special Event",
  "dayOfWeek": "Monday",
  "date": "2026-07-20",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-10",
  "title": "PS 137K Thurs",
  "school": "PS 137K Thurs",
  "address": "123 Main St",
  "subway": "1, 2, 3",
  "type": "Camp",
  "dayOfWeek": "Thursday",
  "date": "2026-07-21",
  "status": "Active",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-1",
  "title": "Residency, PS 137K, Slime Kits, 7/22, every Wed till Sep",
  "school": "PS 137K",
  "address": "121 Saratoga Avenue",
  "subway": "Sutter Av-Rutland Rd (3)",
  "type": "AS Residency",
  "dayOfWeek": "Sunday",
  "date": "2026-07-22",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-16",
  "title": "PS 16x - Slime Party - 7/22",
  "school": "PS 16x",
  "address": "4550 CARPENTER AVENUE",
  "subway": "Nereid Av (2, 5)",
  "type": "Not Defined",
  "dayOfWeek": "Tuesday",
  "date": "2026-07-22",
  "status": "Active",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-17",
  "title": "PS 95K - Residency School Day - 7/23",
  "school": "PS 95K",
  "address": "",
  "subway": "",
  "type": "AS Residency",
  "dayOfWeek": "",
  "date": "2026-07-23",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-12",
  "title": "Staten Island Technical High School - Pop-Up - 7/28",
  "school": "Staten Island Technical High School",
  "address": "485 Clawson Street",
  "subway": "Not found",
  "type": "Not Defined",
  "dayOfWeek": "Tuesday",
  "date": "2026-07-28",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-2",
  "title": "Residency, PS 137K, Slime Kits, 7/22, every Wed till Sep",
  "school": "PS 137K",
  "address": "121 Saratoga Avenue",
  "subway": "Sutter Av-Rutland Rd (3)",
  "type": "AS Residency",
  "dayOfWeek": "Sunday",
  "date": "2026-07-29",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-13",
  "title": "New York Edge PS 309K - Pop-Up - 7/31",
  "school": "New York Edge PS 309K",
  "address": "794 Monroe S, Brooklyn, NY, 11221",
  "subway": "Bedford-Nostrand Avs (G)",
  "type": "Not Defined",
  "dayOfWeek": "Friday",
  "date": "2026-07-31",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-3",
  "title": "Residency, PS 137K, Slime Kits, 7/22, every Wed till Sep",
  "school": "PS 137K",
  "address": "121 Saratoga Avenue",
  "subway": "Sutter Av-Rutland Rd (3)",
  "type": "AS Residency",
  "dayOfWeek": "Sunday",
  "date": "2026-08-05",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-14",
  "title": "PS 137K Summer Program",
  "school": "PS 137K Summer Program",
  "address": "123 Main St",
  "subway": "1, 2, 3",
  "type": "Camp",
  "dayOfWeek": "Saturday",
  "date": "2026-08-05",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-5",
  "title": "—",
  "school": "—",
  "address": "",
  "subway": "",
  "type": "",
  "dayOfWeek": "Monday",
  "date": "2026-08-06",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-15",
  "title": "PS 137K Summer Program",
  "school": "PS 137K Summer Program",
  "address": "123 Main St",
  "subway": "1, 2, 3",
  "type": "Camp",
  "dayOfWeek": "Saturday",
  "date": "2026-08-06",
  "status": "Active",
  "signed": 2,
  "limit": 10,
  "slots": 8,
  "signedUsers": [
   "Ahmet Doe",
   "Ahmet Joe"
  ]
 },
 {
  "id": "evt-4",
  "title": "Residency, PS 137K, Slime Kits, 7/22, every Wed till Sep",
  "school": "PS 137K",
  "address": "121 Saratoga Avenue",
  "subway": "Sutter Av-Rutland Rd (3)",
  "type": "AS Residency",
  "dayOfWeek": "Sunday",
  "date": "2026-08-12",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-18",
  "title": "PS 23K - Pop-Up, Residency School Day, Residency School Day -",
  "school": "\"PS 23K\"",
  "address": "545 Willoughby ave",
  "subway": "Myrtle-Willoughby Avs (G)",
  "type": "Residency School Day",
  "dayOfWeek": "",
  "date": "2026-08-19",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-20",
  "title": "Children's Aid NYC - Residency School Day, Slime Kit - NYC Slime Kit - 8/20",
  "school": "\"Children's Aid NYC\"",
  "address": "",
  "subway": "",
  "type": "Not Defined",
  "dayOfWeek": "Thursday",
  "date": "2026-08-20",
  "status": "Inactive",
  "signed": 0,
  "limit": 10,
  "slots": 10,
  "signedUsers": []
 },
 {
  "id": "evt-21",
  "title": "Pedro Lopez PS 000 - Slime Party, Residency School Day, Residency After School, Slime Kit, Summer Rising, Pop-Up - 8/28",
  "school": "\"Pedro Lopez PS 000\"",
  "address": "141/1 Chambers Street",
  "subway": "Wall Street 5th St, Brooklyn, NY 10001",
  "type": "Not Defined",
  "dayOfWeek": "Friday",
  "date": "2026-08-28",
  "status": "Inactive",
  "signed": 0,
  "limit": 9,
  "slots": 9,
  "signedUsers": []
 },
 {
  "id": "evt-19",
  "title": "PS 343Q - Pop-Up, Residency School Day - 8/31",
  "school": "PS 343Q",
  "address": "45-45 42nd St",
  "subway": "40 St-Lowery St (7, N, Q)",
  "type": "Not Defined",
  "dayOfWeek": "Monday",
  "date": "2026-08-31",
  "status": "Active",
  "signed": 6,
  "limit": 12,
  "slots": 6,
  "signedUsers": [
   "Ahmet Joe",
   "Ahmet JoeTest",
   "Ahmet Test",
   "Ahmet TestV",
   "Ahmet Shamiev",
   "Ahmet Shamiev2"
  ]
 },
 {
  "id": "evt-22",
  "title": "P.S. 197 - THE KINGS HIGHWAY ACADEMY, F26, Pop-Up, Residency School Day, Residency After School, Slime Kit, 10/6",
  "school": "P.S. 197 - THE KINGS HIGHWAY ACADEMY",
  "address": "[Not provided]",
  "subway": "Flatbush Av–Brooklyn College (2, 5)",
  "type": "Residency School Day / Residency After School / Pop-Up / Slime Kit",
  "dayOfWeek": "Tuesday / Thursday",
  "date": "2026-10-06",
  "status": "Active",
  "signed": 0,
  "limit": 8,
  "slots": 8,
  "signedUsers": []
 },
 {
  "id": "evt-24",
  "title": "P.S. 197 - THE KINGS HIGHWAY ACADEMY, F26, Pop-Up, Residency School Day, Residency After School, Slime Kit, 10/6",
  "school": "P.S. 197 - THE KINGS HIGHWAY ACADEMY",
  "address": "[Not provided]",
  "subway": "Flatbush Av–Brooklyn College (2, 5)",
  "type": "Residency School Day / Residency After School / Pop-Up / Slime Kit",
  "dayOfWeek": "Tuesday / Thursday",
  "date": "2026-10-08",
  "status": "Active",
  "signed": 0,
  "limit": 8,
  "slots": 8,
  "signedUsers": []
 },
 {
  "id": "evt-6",
  "title": "—",
  "school": "—",
  "address": "",
  "subway": "",
  "type": "",
  "dayOfWeek": "",
  "date": "2026-10-12",
  "status": "Active",
  "signed": 4,
  "limit": 10,
  "slots": 6,
  "signedUsers": [
   "Ahmet Doe",
   "Ahmet Joe",
   "Ahmet JoeTest",
   "Ahmet Shamiev"
  ]
 },
 {
  "id": "evt-23",
  "title": "P.S. 197 - THE KINGS HIGHWAY ACADEMY, F26, Pop-Up, Residency School Day, Residency After School, Slime Kit, 10/6",
  "school": "P.S. 197 - THE KINGS HIGHWAY ACADEMY",
  "address": "[Not provided]",
  "subway": "Flatbush Av–Brooklyn College (2, 5)",
  "type": "Residency School Day / Residency After School / Pop-Up / Slime Kit",
  "dayOfWeek": "Tuesday / Thursday",
  "date": "2026-10-13",
  "status": "Active",
  "signed": 0,
  "limit": 8,
  "slots": 8,
  "signedUsers": []
 },
 {
  "id": "evt-27",
  "title": "P.S. 197 - THE KINGS HIGHWAY ACADEMY, F26, Pop-Up, Residency School Day, Residency After School, Slime Kit, 10/6",
  "school": "P.S. 197 - THE KINGS HIGHWAY ACADEMY",
  "address": "[Not provided]",
  "subway": "Flatbush Av–Brooklyn College (2, 5)",
  "type": "Residency School Day / Residency After School / Pop-Up / Slime Kit",
  "dayOfWeek": "Tuesday / Thursday",
  "date": "2026-10-15",
  "status": "Active",
  "signed": 0,
  "limit": 8,
  "slots": 8,
  "signedUsers": []
 },
 {
  "id": "evt-25",
  "title": "P.S. 197 - THE KINGS HIGHWAY ACADEMY, F26, Pop-Up, Residency School Day, Residency After School, Slime Kit, 10/6",
  "school": "P.S. 197 - THE KINGS HIGHWAY ACADEMY",
  "address": "[Not provided]",
  "subway": "Flatbush Av–Brooklyn College (2, 5)",
  "type": "Residency School Day / Residency After School / Pop-Up / Slime Kit",
  "dayOfWeek": "Tuesday / Thursday",
  "date": "2026-10-20",
  "status": "Active",
  "signed": 0,
  "limit": 8,
  "slots": 8,
  "signedUsers": []
 },
 {
  "id": "evt-26",
  "title": "P.S. 197 - THE KINGS HIGHWAY ACADEMY, F26, Pop-Up, Residency School Day, Residency After School, Slime Kit, 10/6",
  "school": "P.S. 197 - THE KINGS HIGHWAY ACADEMY",
  "address": "[Not provided]",
  "subway": "Flatbush Av–Brooklyn College (2, 5)",
  "type": "Residency School Day / Residency After School / Pop-Up / Slime Kit",
  "dayOfWeek": "Tuesday / Thursday",
  "date": "2026-10-22",
  "status": "Active",
  "signed": 0,
  "limit": 8,
  "slots": 8,
  "signedUsers": []
 }
];

export const STAFF = [
 {
  "id": "s1",
  "name": "Ahmet Doe",
  "email": "ahmet.doe@splatlab.co",
  "rate": 32
 },
 {
  "id": "s2",
  "name": "Ahmet Joe",
  "email": "ahmet.joe@splatlab.co",
  "rate": 30
 },
 {
  "id": "s3",
  "name": "Ahmet JoeTest",
  "email": "ahmet.joetest@splatlab.co",
  "rate": 28
 },
 {
  "id": "s4",
  "name": "Ahmet Test",
  "email": "bakero.app@gmail.com",
  "rate": 28
 },
 {
  "id": "s5",
  "name": "Ahmet Shamiev",
  "email": "ahmet.shamiev@splatlab.co",
  "rate": 45
 },
 {
  "id": "s6",
  "name": "Ahmet TestV",
  "email": "ahmet.testv@splatlab.co",
  "rate": 30
 },
 {
  "id": "s7",
  "name": "Ahmet Shamiev2",
  "email": "ahmet.shamiev2@splatlab.co",
  "rate": 38
 }
];
